### ISSUE TITLE
The barcode names aren't deleted correctly

### ISSUE THREAD

**Issue by Vincentwang987** [AndrewPerson/Lit-Paragon-Client#116] opened 2022-05-04 08:53 UTC
In the barcode extension, when trying to delete any barcode, the barcode will automatically delete the last barcode.

Video

https://user-images.githubusercontent.com/93361820/166650429-0d0995e6-94e6-498e-a55d-9b5513afa4c6.mp4

**Comment by Vincentwang987** [comment] 2022-05-04 10:48
It seems like the barcode itself is correct but the names of the barcodes are messed up

**Comment by AndrewPerson** [comment] 2022-05-04 21:23
Dear Vincent,
Thanks for bringing this to my attention! I've been able to reproduce this on my phone. I believe it's caused by Lit's dom-diffing being a bit _too_ aggressive. Hopefully, I should be able to fix this soon.

Sincerely,
Andrew

**Comment by AndrewPerson** [comment] 2022-05-05 09:46
Well, this should be fixed as of the latest version of the Barcodes extension!

**Closed by AndrewPerson** 2022-05-05 09:46 UTC
